spring.application.name=paycore-backend
server.port=8080

# Database Configuration (Default H2 for local dev, overridable by environment variables for Docker PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:paycoredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security & JWT Secrets
paycore.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
paycore.app.jwtExpirationMs=86400000

# CORS Configuration
paycore.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost,http://localhost:80}
